name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 91.184.244.231
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/wordly-bot
            git pull
            docker compose up -d --build

